<h3> Template tags </h3>
<ul>
    <li>[distance] - Total distance of the activity
    <li>[description] - Description of the activity
    <li>[duration] - Duration of the activity
    <li>[photo] - The first photo attached to the activity
    <li>[map] - A google map of the route
    <li>[photoOrMap] - Display a photo if there is one otherwise display map
    <li>[max_hr] - Maximum heart rate
    <li>[avg_hr] - Average heart rate
    <li>[elevation] - Total elevation of the activity
    <li>[name] - Name of the activity
    <li>[speed] - Running pace or riding speed
    <li>[time] Start time of the activity
    <li>[type] Type of the activity
</ul>