</form>
<form action="options-general.php?page=astrava_admin&tab=templates" method="post"/>
<input name="state" value="save" type="hidden" />
<h2>Create New Template</h2>
<table class="form-table">
    <tr>
        <th scope="row">Activity Type:</th>
        <td><input type="text" name="template_name" /></td>
    </tr>
    <tr>
        <td scope="row" valign="top">
        <strong>Available Tags</strong>
        <ul>
            <li>[distance]</li>
            <li>[description]</li>
            <li>[duration]</li>
            <li>[photo]</li>
            <li>[map]</li>
            <li>[photoOrMap]</li>
            <li>[max_hr]</li>
            <li>[avg_hr]</li>
            <li>[elevation]</li>
            <li>[name]</li>
            <li>[speed]</li>
            <li>[time]</li>
            <li>[type]</li>
        </ul>
        </td>
        <td valign="top"> 
        <?php
            wp_editor('', 'template_code', 
                    array ('media_buttons' => false, 
                           'textarea_name' => 'template_code',
                           'textarea_rows' => 12,
                           'classes' => 'template_editor')); 
            ?></td>
    </tr>
</table>