<div id="astrava-activities">
<?php if (count(activities) > 0):?>

Click the link to insert this activity at the edit point.
<ul>
    <?php foreach ($activities as $activity): ?>
        <li>
            <a class="astrava-editor-link" 
                data-activity-id="<?php echo $activity->id; ?>"><?php echo $activity->name; ?></a><br>
            <em><?php echo $activity->type; ?> - <?php echo human_time_diff(strtotime($activity->start_date), time()); ?> ago</em>
        </li>
    <?php endforeach; ?>
</ul>

<?php else: ?>
<div> No recent activities found.</div>  
<?php endif; ?>
<?php if (count($activities == 5)): ?>
<a class="astrava-nav" data-page="<?php echo $current_page + 1 ?>">&lt; older</a>
<?php endif; ?>
<?php if ($current_page - 1 > 0): ?>
<a class="astrava-nav" data-page="<?php echo $current_page - 1 ?>">newer &gt;</a>
<?php endif; ?>
</div>