<div id="strava_map"></div>
<script type="text/javascript" src="http://maps.google.com/maps/api/js?key=AIzaSyAoAUyOJ-PoLBa8QGGyWNf_A1-6Mh8f84Q&libraries=geometry&amp;sensor=false">
</script>
<style type="text/css"> #strava_map {width:100%;height:300px;}</style> 
<script type='text/javascript'>
    var map = new google.maps.Map(document.getElementById('strava_map'), {
      center: {lat: <?php echo $lat; ?>, 
      		   lng: <?php echo $lng; ?>},
      zoom: 15
    });

    var decodedPath = google.maps.geometry.encoding.decodePath("<?php echo $polyline ?>");

    var setRegion = new google.maps.Polyline({
				        path: decodedPath,
				        strokeColor: "#FF0000",
				        strokeOpacity: 1.0,
				        strokeWeight: 2,
				        map: map
				    });

    var points = setRegion.getPath().getArray();
    var bounds = new google.maps.LatLngBounds();
    for (var n = 0; n < points.length ; n++){
        bounds.extend(points[n]);
    }
    
    center = bounds.getCenter();
    map.setCenter(center);
</script>